app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

// Page routes

Route::get('about', 'PagesController@about');

Route::get('info', 'PagesController@info');

// Articles routes

Route::resource('articles', 'ArticlesController');

// Products routes

Route::resource('products', 'ProductsController');

app/Article.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
    protected $table = 'articles';

    protected $fillable = ['title', 'body', 'excerpt', 'published_at'];

    public function setPublishedAtAttribute($date) //setFieldAttribute
    {
        $this->attributes['published_at'] = Carbon::createFromFormat('Y-m-d', $date);
    }

    public function setPasswordAttribute($data)
    {
        $this->attributes['password'] = bcrypt($data);
    }

    public function setTitleAttribute($data)
    {
        $this->attributes['title'] = 'Laravel - ' . $data;
    }

    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', Carbon::now());
    }

    public function scopeUnpublished($query)
    {
        return $query->where('published_at', '>', Carbon::now());
    }

    public function user()
    {
        $this->belongsTo('App\User');
    }

    public function tags()
    {
        return $this->belongsToMany('App\Tag');
    }

}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\Tag;
use App\User;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests\ArticleCreateRequest;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;

class ArticlesController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth', ['except' => 'index']);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::latest('published_at')->published()->get();

        return view('articles.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::lists('name', 'id');

        return view('articles.create', compact('tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleCreateRequest $request)
    {
        $request = $request->all();

        $article = new Article($request);

        Auth::user()->articles()->save($article);

        $article->tags()->attach($request['tags']);

        \Session::flash('flash_message', 'Uw artikel is aangemaakt');

        return redirect('articles');
    }

    /*public function store(Request $request){
        $this->validate($request, ['title' => 'required', 'body' => 'required']);

        $article = new Article($request->all());

        $article->save();

        return redirect('articles');
    }*/

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $article = Article::find($id); // throw error when article not found

        if(is_null($article)){
            abort(404);
        }

        return view('articles.show', compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id); // throw error when article not found

        return view('articles.edit', compact('article'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleCreateRequest $request, $id)
    {
        $article = Article::findOrFail($id);
        $article->update($request->all());

        return redirect('articles/' . $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::findOrFail($id);
        $article->destroy($id);

        return redirect('articles');
    }
}

resources/views/articles/_form.blade.php
<div class="form-group">
    {!! Form::label('title', 'Title:') !!}
    {!! Form::text('title', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('excerpt', 'Excerpt:') !!}
    {!! Form::textarea('excerpt', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('body', 'Body:') !!}
    {!! Form::textarea('body', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('published_at', 'Must be published at:') !!}
    {!! Form::input('date', 'published_at', date('Y-m-d'), ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('tags', 'Tags:') !!}
    {!! Form::select('tags[]', $tags, null, ['class' => 'form-control', 'multiple']) !!}
</div>

<div class="form-group">
    {!! Form::submit($buttontext, ['class' => 'btn btn-primary form-control']) !!}
</div>

resources/views/articles/create.blade.php
@extends('app')

@section('content')
    <h1>Maak artikel aan</h1>

    {!! Form::open(['url' => 'articles']) !!}

        @include('articles._form', ['buttontext' => 'Create'])

    {!! Form::close() !!}

@stop

resources/views/articles/edit.blade.php
@extends('app')

@section('content')
    <h1>Update artikel met id {{ $article->id }}</h1>

    {!! Form::model($article, ['method' => 'PATCH', 'url' => 'articles/' . $article->id]) !!}

        @include('articles._form', ['buttontext' => 'Wijzigen'])

    {!! Form::close() !!}

@stop

resources/views/articles/index.blade.php
@extends('app')

@section('content')
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Articles <small>Overview</small>
            </h1>
            <a style="float: right;position: absolute;top: 0;right: 0;" class="btn btn-primary" href="{{ action('ArticlesController@create') }}">Artikel aanmaken</a>
        </div>
    </div>
    <!-- /.row -->



    @if(count($articles) > 0)
        @foreach($articles as $article)

            <div class="row">
                <div class="col-lg-12 well">
                    <h2 class="page-header">{{ $article->title }}</h2>
                    <p class="lead">{{ $article->excerpt }}</p>
                    <a href="{{ action('ArticlesController@show', [$article->id]) }}">Lees Meer</a>

                    <div style="float:right">
                        <a stlye="float:left;" class="btn btn-default" href="{{ action('ArticlesController@edit', [$article->id]) }}">Edit</a>

                        <form style="float:right; margin-left:5px;" action="{{ URL::route('articles.destroy',$article->id) }}" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <button class="btn btn-danger">Delete</button>
                        </form>

                    </div>
                </div>
            </div>

        @endforeach
    @else
        <p>Er zijn nog geen artikelen beschikbaar.</p>
    @endif
@stop

resources/views/articles/show.blade.php
@extends('app')

@section('content')
    <h1>{{ $article->title }}</h1>
    <p>{{ $article->body }}</p>
    <p>Tags:</p>
    @foreach($article->tags as $tag)
        <span>{{ $tag->name }}</span>
    @endforeach

    <hr />
@stop